#!/bin/bash

message_error () {
	echo "Help:"
	echo "The flags to use are: -y [Youtube URL] -s [full, big, medium, small, audio] -f [File name]"
	exit 0
}

while getopts "y:s:f:" flags; do
	case $flags in
		y)
			URL=$OPTARG
			;;
		s)
			DISPLAY_SIZE=$OPTARG
			;;
		f)
			FILE=$OPTARG
			;;
		*)
			message_error
			;;
	esac
done

if [ $OPTIND -eq 1 ];
then
	message_error
fi

case $DISPLAY_SIZE in
	full)
		DISPLAY_SIZE="0 0 0 0"
		;;
	big)
		DISPLAY_SIZE="0 0 1280 720"
		;;
	medium)
		DISPLAY_SIZE="0 0 854 480"
		;;
	small)
		DISPLAY_SIZE="0 0 640 360"
		;;
	audio)
		DISPLAY_SIZE="0 0 1 1"
		;;
esac

if [ -z ${URL} ];
then
	omxplayer -o hdmi --vol -2700 -I --win "${DISPLAY_SIZE}" "${FILE}"
else
	omxplayer -o hdmi --vol -2700 -I --win "${DISPLAY_SIZE}" "$(youtube-dl -g -f 'best[height>=480]/best[height<=1080]/best[ext=mp4]' ${URL})"
fi

