#!/bin/bash

URL=$(zenity --entry --height=100 --width=500 --text="URL del playlist")

if [ ! -z $URL ]
then
	TARGET=$(zenity --file-selection --directory \
	--height=500 --width=500 \
	--title="Descarga en ...")

	if [ ! -z $TARGET ]
	then
		youtube-dl -i -f mp4 --yes-playlist -o "$TARGET/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" $URL
	fi
fi
